// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb70FE66uQiBP5Tas4h-PYqeXo4WcYE9g',
    appId: '1:902629826920:web:48ddb21a6736bd946bb6dd',
    messagingSenderId: '902629826920',
    projectId: 'merveille-investments',
    authDomain: 'merveille-investments.firebaseapp.com',
    storageBucket: 'merveille-investments.firebasestorage.app',
    measurementId: 'G-YRF7Y61Q2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1czW_JpHtmSc3ifNnu5GwHNnRHBA4QB8',
    appId: '1:902629826920:android:e71bf951cae169106bb6dd',
    messagingSenderId: '902629826920',
    projectId: 'merveille-investments',
    storageBucket: 'merveille-investments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkzjddpjke3s_saNMTKFeG0x2BBjDf1Ow',
    appId: '1:902629826920:ios:b70b59b2d489fa106bb6dd',
    messagingSenderId: '902629826920',
    projectId: 'merveille-investments',
    storageBucket: 'merveille-investments.firebasestorage.app',
    iosBundleId: 'com.example.miapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkzjddpjke3s_saNMTKFeG0x2BBjDf1Ow',
    appId: '1:902629826920:ios:b70b59b2d489fa106bb6dd',
    messagingSenderId: '902629826920',
    projectId: 'merveille-investments',
    storageBucket: 'merveille-investments.firebasestorage.app',
    iosBundleId: 'com.example.miapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb70FE66uQiBP5Tas4h-PYqeXo4WcYE9g',
    appId: '1:902629826920:web:209bb518ea343a266bb6dd',
    messagingSenderId: '902629826920',
    projectId: 'merveille-investments',
    authDomain: 'merveille-investments.firebaseapp.com',
    storageBucket: 'merveille-investments.firebasestorage.app',
    measurementId: 'G-618SVH7EFM',
  );
}
